### PR TITLE
Add third post on faces.py

### PR DESCRIPTION
**Pull request by willingc**
A videoclip of yesterday's program running. Intro to a similar but slightly more complex program faces.py

### CODE REVIEW

**Comment by ntoll** [comment]
If you look at how video is embedded in the Monifa.html file you'll see I can make it automatically responsive. ;-)

Viz:

```
<div class="video-container">
... iframe ...
</div>
```

**Comment by ntoll** [comment]
Actually, I'll do it right now... ;-)

**Comment by ntoll** [comment]
Yay! :shipit: :-)

**Comment by willingc** [comment]
Ooh cool tip on the responsive video. Will include in next post :movie_camera:

**Pull request merged**
