### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by richpeters**
With love from team Blanc

### CODE REVIEW

**Comment by ntoll** [comment]
THAT IS TOTALLY AWESOME.

Couple of things...

1) It turns my laptop into a hair-dryer as the fan comes on (latest Firefox on Debian Jessie). Is there a less CPU intensive version..? (E.g. the globe spins but the satellites are static, or just the micro:bit bounces etc...) Perhaps I could implement a toggle to switch various levels of animation on/off..?
2) There's no way to get back to the front page. Perhaps the "World Tour" header should link back to it..? Or am I missing something here??? (Probably!) :-)
3) You need to be acknowledged in some way... please add a footer with a link to Blanc. ;-)

**Comment by richpeters** [comment]
We think so too!

In reference to performance, I'll optimise the SVG assets further and reduce the number of animations. However, unless we remove assets it'll be difficult to improve FPS and CPU load dramatically.

I'll make the "micro:bit world tour" in the header a link back to the homepage as you request.

I'll let Steve decide if he wants to be mentioned! ha

**Comment by hawkz** [comment]
We could just make the globe and stars spin on hover of the header section, at least then it's not a permanent effect?

**Comment by ntoll** [comment]
Sounds like a great compromise. :-) :+1:

**Comment by hawkz** [comment]
I think we're there @ntoll

**Pull request merged**
