### PR TITLE
Add second post on program structure for Meena

### PR DESCRIPTION
**Pull request by willingc**
Compare having a party and programming. :birthday:

### CODE REVIEW

**Comment by ntoll** [comment]
Hi @willingc! Great stuff.

If you don't mind I'll replace the code-as-images with code-as-text so people can cut'n'paste your wonderful examples.

Great stuff! ;-)

**Comment by ntoll** [comment]
By the way... there's a danger I'm just going to keep on typing "great stuff" about this contribution. It's such a wonderful introduction for 11yo. I can imagine teachers and students lapping this up.

Great stuff! 

:-)

**Comment by ntoll** [comment]
Merged manually.

**Comment by willingc** [comment]
@ntoll Thanks! Totally cool with you making the examples cut and paste. As an FYI, the file is in my github account under the mybit repo. :sunflower:

**Pull request closed without merging**
